FROM node:16 AS frontend

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps

COPY frontend/ ./
RUN npm run build
# Use an Nginx image to serve your frontend app
FROM nginx:alpine
WORKDIR /app

# Copy the built frontend into the Nginx container
COPY --from=frontend /app/frontend/build /app/frontend/build

# Copy your Nginx configuration
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose the port Nginx will run on
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
